name = "konvy-log-relay"
main = "worker/index.js"
compatibility_date = "2024-01-30"
node_compat = true

[vars]
# 填入 Supabase 信息
SUPABASE_URL = "https://dehcpksgjhyvoyccafnj.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlaGNwa3Nnamh5dm95Y2NhZm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NzU5MzAsImV4cCI6MjA4NTU1MTkzMH0.f51lBltot16OF2HmifWqUdl4sOe1SOO7f4c5k5rMAqg"
AUTH_TOKEN = "konvy-debug-2026"
